CREATE Database TPI_BasesDeDatos;
go
COLLATE Latin1_General_CI_AI;
go
USE TPI_BasesDeDatos;
go
---- AGUSTIN ------
CREATE TABLE Rol(
	IDRol INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(20) NOT NULL
)
CREATE TABLE Usuarios(
	IDUsuario BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1),
	IDRol INT NOT NULL FOREIGN KEY REFERENCES Rol (IDRol),
	Usuario VARCHAR(20) NOT NULL UNIQUE,
	Clave VARCHAR(20) NOT NULL,
	Activo BIT
)
CREATE TABLE Recepcionista(
	IDRecepcionista BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1),
	IDUsuario BIGINT NOT NULL FOREIGN KEY REFERENCES Usuarios (IDUsuario),
	Nombre VARCHAR(20) NOT NULL,
	Apellido VARCHAR(20) NOT NULL, 
	Dni VARCHAR(10) NOT NULL UNIQUE,
	Legajo VARCHAR(5) NOT NULL UNIQUE,
	Telefono VARCHAR(15),
	Correo VARCHAR(50),
	Activo BIT
)
---- FRANCO -----
CREATE TABLE Dueño (
    IDDueño INT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Dni VARCHAR(20) UNIQUE NOT NULL,
	Legajo VARCHAR(20) UNIQUE NOT NULL,
    Telefono VARCHAR(20),
    Correo VARCHAR(100),
    Domicilio VARCHAR(150),
    CantMascotas INT,
    Activo SMALLINT DEFAULT 1
);

CREATE TABLE Mascota (
    IDMascota INT PRIMARY KEY,
    IDDueño INT NOT NULL FOREIGN KEY REFERENCES Dueño(IDDueño),
    Nombre VARCHAR(50) NOT NULL,
    Edad INT CHECK (Edad >= 0),
    FechaNacimiento DATE,
    Peso DECIMAL CHECK (Peso >= 1),
    Tipo VARCHAR(30),
    Raza VARCHAR(50),
    Sexo SMALLINT CHECK (Sexo IN (0,1)),
    Activo SMALLINT DEFAULT 1
	FechaRegistro DATETIME DEFAULT CURRENT_TIMESTAMP;
);
----- SOL ----
CREATE TABLE Veterinario (
	IDVeterinario BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	IDUsuario BIGINT NOT NULL FOREIGN KEY REFERENCES Usuarios (IDUsuario),
	Nombre VARCHAR(20) NOT NULL,
	Apellido VARCHAR(20) NOT NULL, 
	Dni VARCHAR(10) NOT NULL UNIQUE,
	Matricula VARCHAR(5) NOT NULL UNIQUE,
	Telefono VARCHAR(15),
	Correo VARCHAR(50),
	Activo BIT
);

CREATE TABLE FichaConsulta(
	IDFicha BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	IDMascota BIGINT NOT NULL FOREIGN KEY REFERENCES Mascota (IDMascota),
	IDVeterinario BIGINT NOT NULL FOREIGN KEY REFERENCES Veterinario (IDVeterinario),
	Diagnostico VARCHAR (50),
	Descripcion VARCHAR (300),
	Fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
	Activo BIT
);

---- NICOLAS ------

CREATE TABLE Cobros (
    IDCobro BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
    IDTurno BIGINT NOT NULL FOREIGN KEY REFERENCES Turnos(IDTurno),
    IDRecepcionista BIGINT NOT NULL FOREIGN KEY REFERENCES Recepcionista(IDRecepcionista),
    FormaPago VARCHAR(30) NOT NULL,
    Costo DECIMAL(10,2) NOT NULL CHECK (Costo >= 0),
    Fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    Activo BIT
);

CREATE TABLE Turnos (
    IDTurno BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
    IDMascota BIGINT NOT NULL FOREIGN KEY REFERENCES Mascota(IDMascota),
    IDVeterinario BIGINT NOT NULL FOREIGN KEY REFERENCES Veterinario(IDVeterinario),
    FechaHora DATETIME NOT NULL,
    Activo BIT
);
